
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.RadioButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import testcrud.KoneksiDB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ridha Nadhira Febyan
 */
public class frmMain extends javax.swing.JFrame {

    String nol_jam="";
    String nol_menit="";
    String nol_detik="";
    private String tanggal;
    
    public frmMain() {
        initComponents();
        selectData();
        setJam();
        setTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        labeltgl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbp = new javax.swing.JRadioButton();
        rbl = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        kls = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        almat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tmpt = new javax.swing.JTextField();
        tgllhr = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        del = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        ref = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("The Real Informatic School");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FORM BIODATA SISWA TELKOM SCHOOL MALANG");

        labeljam.setForeground(new java.awt.Color(204, 204, 255));
        labeljam.setText("Jam");

        labeltgl.setForeground(new java.awt.Color(204, 204, 255));
        labeltgl.setText("Tanggal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labeltgl, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(labeljam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(labeltgl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labeljam)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 100);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ISIAN DATA SISWA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("JENIS KELAMIN");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 250, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NIS");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 20, 50, 20);

        nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel2.add(nama);
        nama.setBounds(10, 100, 190, 30);

        nis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nisActionPerformed(evt);
            }
        });
        jPanel2.add(nis);
        nis.setBounds(10, 40, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("NAMA");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 80, 110, 20);

        rbp.setBackground(new java.awt.Color(102, 255, 102));
        buttonGroup1.add(rbp);
        rbp.setText("Perempuan");
        rbp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpActionPerformed(evt);
            }
        });
        jPanel2.add(rbp);
        rbp.setBounds(110, 270, 100, 23);

        rbl.setBackground(new java.awt.Color(102, 255, 102));
        buttonGroup1.add(rbl);
        rbl.setText("Laki-Laki");
        rbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblActionPerformed(evt);
            }
        });
        jPanel2.add(rbl);
        rbl.setBounds(10, 270, 90, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("KELAS");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 300, 50, 20);

        kls.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klsActionPerformed(evt);
            }
        });
        jPanel2.add(kls);
        kls.setBounds(10, 320, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ALAMAT");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 410, 110, 20);

        email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email);
        email.setBounds(10, 380, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("EMAIL");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 360, 110, 20);

        almat.setColumns(20);
        almat.setRows(5);
        jScrollPane1.setViewportView(almat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 430, 220, 70);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("TANGGAL LAHIR");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 200, 130, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("TEMPAT LAHIR");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 140, 130, 20);

        tmpt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tmpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmptActionPerformed(evt);
            }
        });
        jPanel2.add(tmpt);
        tmpt.setBounds(10, 160, 160, 30);
        jPanel2.add(tgllhr);
        tgllhr.setBounds(10, 220, 150, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 120, 300, 510);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setLayout(null);

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("SAVE");
        save.setMargin(new java.awt.Insets(-5, -5, -5, -5));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save);
        save.setBounds(10, 11, 81, 38);

        del.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        del.setText("DELETE");
        del.setMargin(new java.awt.Insets(-5, -5, -5, -5));
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel3.add(del);
        del.setBounds(97, 11, 81, 38);

        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.setMargin(new java.awt.Insets(-5, -5, -5, -5));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear);
        clear.setBounds(184, 11, 81, 38);

        ref.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ref.setText("REFRESH");
        ref.setMargin(new java.awt.Insets(-10, -10, -10, -10));
        ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refActionPerformed(evt);
            }
        });
        jPanel3.add(ref);
        ref.setBounds(271, 11, 81, 38);

        edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit.setText("EDIT");
        edit.setMargin(new java.awt.Insets(-5, -5, -5, -5));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit);
        edit.setBounds(358, 11, 81, 38);

        print.setBackground(new java.awt.Color(204, 204, 255));
        print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        print.setText("PRINT");
        print.setMargin(new java.awt.Insets(-5, -5, -5, -5));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print);
        print.setBounds(449, 11, 81, 38);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(330, 120, 540, 60);

        jPanel4.setBackground(new java.awt.Color(0, 204, 102));

        jTable1.setBackground(new java.awt.Color(153, 255, 153));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Tempat", "Tanggal", "JKelamin", "Kelas", "Email", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(330, 190, 540, 440);

        setBounds(0, 0, 898, 686);
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nisActionPerformed

    private void rbpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbpActionPerformed

    private void rblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rblActionPerformed

    private void klsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_klsActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       String tanggal = dateFormat.format(tgllhr.getDate());
       String JK = "";
       if(rbl.isSelected()){
           JK = "L";
       } else {
           JK="P";
       }
        if(nis.getText().equals("") || nama.getText().equals("") || tmpt.getText().equals("") 
                || tanggal.equals("") || kls.getText().equals("")
                || email.getText().equals("") || almat.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Harap lengkapi data Anda", "Error", JOptionPane.WARNING_MESSAGE);
            }else{           
            String SQL = "INSERT INTO t_siswa (NIS,Nama,Tempat,Tanggal,JKelamin,Kelas,Email,Alamat)"
                   +"VALUES('"+nis.getText()+"','"+nama.getText()
                   +"','"+tmpt.getText()+"','"+tanggal+"','"+JK+"',"
                    +"'"
                   +kls.getText()+"','"+email.getText()+"','"                   
                   +almat.getText()+"')";
            
           /*String SQL = "INSERT INTO t_siswa VALUES ('"+nis.getText()+"', '"+nama.getText()
                   +"', '"+tanggal+"', '"+JK+"', '"+kls.getText()+"', '"+email.getText()+"'; '"
                   +tmpt.getText()+"', '"
                   +almat.getText()+"')";
             
           String SQL = "INSERT INTO t_siswa VALUES "
                   +"('"
                   +nis.getText()+"', '"
                   +nama.getText()+"', '"
                   +tmpt.getText()+"', '"
                   +tanggal+"', '" +JK+"', '"
                   +kls.getText()+"', '"
                   +email.getText()+"', '"
                   +almat.getText()+"')";
             */
           int status = KoneksiDB.execute(SQL);
           
           if(status == 1){
               JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
               selectData();
           }else{
               JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
           }
                   
    }         
    }//GEN-LAST:event_saveActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
       int baris =jTable1.getSelectedRow();
       if(baris != -1){
           String NIS = jTable1.getValueAt(baris, 0).toString();
           String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
           int status = KoneksiDB.execute(SQL);
           if(status ==1)
           {
               JOptionPane.showMessageDialog(this, "Data berhadil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           }
           else{
               JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
           }
       }else
       {
           JOptionPane.showMessageDialog(this,"Pilih baris data terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
       }
           
    }//GEN-LAST:event_delActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        nis.setText("");
        nama.setText("");
        tmpt.setText("");
        tgllhr.setDate(null);
        kls.setText("");
        buttonGroup1.clearSelection();
        email.setText("");
        almat.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refActionPerformed
            selectData();
    }//GEN-LAST:event_refActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       String tanggal = dateFormat.format(tgllhr.getDate());    
        if("".equals(nis.getText()) || "".equals(tmpt.getText())||"".equals(almat.getText()) || "".equals(kls.getText()) || "".equals(nama.getText()) || "".equals(email.getText()))
            {
                JOptionPane.showMessageDialog(this, "Harap lengkapi data", "Error", JOptionPane.WARNING_MESSAGE);
            }
            else{
                String JK = "";
                if(rbl.isSelected()){
                    JK = "L";
                }
                else{
                    JK = "P";
                }
                
                String SQL = "UPDATE t_siswa SET "
                        +"Nama='"+nama.getText()+"',"
                        +"Tempat='"+tmpt.getText()+"'," 
                        +"Tanggal='"+tanggal+"',"                      
                        +"JKelamin='"+JK+"',"
                        +"Kelas='"+kls.getText()+"',"
                        +"Email='"+email.getText()+"',"
                        +"Alamat='"+almat.getText()+"'"
                        +"' WHERE NIS='"+nis.getText()+"'";
            
            int status = KoneksiDB.execute(SQL);
            if (status ==0){
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else{
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
            }
    }//GEN-LAST:event_editActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int baris = jTable1.getSelectedRow();
        if(baris != -1){
            nis.setText(jTable1.getValueAt(baris,0).toString());
            nama.setText(jTable1.getValueAt(baris,1).toString());
            tmpt.setText(jTable1.getValueAt(baris,2).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try{
                dateFormat = date.parse(jTable1.getValueAt(baris,3).toString());
            }
            catch(ParseException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            tgllhr.setDate(dateFormat);
            String JK = jTable1.getValueAt(baris,4).toString();
            if(JK.equals("Laki-Laki")){
                rbl.setSelected(true);
            }else
                rbp.setSelected(true);
            
            kls.setText(jTable1.getValueAt(baris,5).toString());
            email.setText(jTable1.getValueAt(baris,6).toString());
            almat.setText(jTable1.getValueAt(baris,7).toString());
            
        }
            

    }//GEN-LAST:event_jTable1MouseClicked

    private void tmptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmptActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)");
            try{
            jTable1.print(JTable.PrintMode.FIT_WIDTH,header,footer,true,null,true,null);
            }catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea almat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kls;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltgl;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JButton print;
    private javax.swing.JRadioButton rbl;
    private javax.swing.JRadioButton rbp;
    private javax.swing.JButton ref;
    private javax.swing.JButton save;
    private com.toedter.calendar.JDateChooser tgllhr;
    private javax.swing.JTextField tmpt;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NIS","Nama","Tempat","Tanggal","JKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                String NIS = rs.getString(1);
                String Nama = rs.getString(2);
                String Tempat = rs.getString(3);
                String Tanggal = rs.getString(4);
                String JKelamin = "";
                if("L".equals(rs.getString(5))){
                    JKelamin = "Laki-laki";
                }else{
                    JKelamin = "Perempuan";
                }
                String Kelas = rs.getString(6);
                String Email = rs.getString(7);
                String Alamat = rs.getString(8);
                String data[] = {NIS,Nama,Tempat,Tanggal,JKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(dtm);
    }
    
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new 
        java.text.SimpleDateFormat("dd/MM/yyyy");
        labeltgl.setText(kal.format(skrg));
    }
    public void setJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }if(nilai_menit <= 9){
                    nol_menit = "0";
                }if(nilai_detik <=9){
                    nol_detik = "0";
                }
                String jam = nol_jam+Integer.toString(nilai_jam);
                String menit = nol_menit+Integer.toString(nilai_menit);
                String detik = nol_detik+Integer.toString(nilai_detik);
                labeljam.setText("Jam "+jam+":"+menit+":"+detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
}
